### ISSUE TITLE
Time Stamp generated unit stamp cannot be applied to units

### ISSUE THREAD

**Issue by Ratvar** [Tempus/Disciple-Monster-Train#117]
Eat a unit, try to apply buffs to a unit, fail. Tested stamps from friendly and enemy units, working the same
![image](https://user-images.githubusercontent.com/22855970/96291870-6458ac80-0ff1-11eb-9ed5-8ecfcd0fa4f9.png)

**Comment by Tempus** [comment]
Fixed
