### ISSUE TITLE
Wardmaster creates the wards after combat when descending during combat via Gravity/Shifter

### ISSUE THREAD

**Issue by Tempus** [Tempus/Disciple-Monster-Train#166]
Expected: Wardmaster moves down in combat due to gravity or shifter, and creates a ward. During that combat round, the ward attacks.

Actual: New ward is not created until after the combat, this was due to the concurrent list additions bug. It should be possible to fix this if it's desired behaviour still.

**Comment by RisingDusk** [comment]
OBE because Wardmaster no longer triggers on Relocate and now triggers on Resolve.
