### ISSUE TITLE
Possible bug with Status Update

### ISSUE THREAD

**Issue by Tempus** [Tempus/Disciple-Monster-Train#196]

**Comment by Jmaxwellsdemon** [comment]
This may be the same bug I was just experiencing.

I have attached a video of this bug on the Fel fight.

**Comment by Jmaxwellsdemon** [comment]
https://youtu.be/y2IfroRvkU0 


Had to link, but this is the video I took.

**Comment by Tempus** [comment]
I believe this is fixed, pushing a fix in next update
