### ISSUE TITLE
Rewind tooltip in brackets seems to be unaffected by First Hellpact plus 3 effect

### ISSUE THREAD

**Issue by Tempus** [Tempus/Disciple-Monster-Train#217]
![image](https://user-images.githubusercontent.com/117361/97079108-343b7b80-15a6-11eb-91a2-ebea441112d6.png)

**Comment by Tempus** [comment]
Also it didn't return 6 cards from the pile

**Comment by RisingDusk** [comment]
Fixed in ebe479a.
