### ISSUE TITLE
Wards have no puns

### ISSUE THREAD

**Issue by Tempus** [Tempus/Disciple-Monster-Train#76]
Really I feel like there are probably a lot of missed opportunities here.

**Comment by isauteikisa** [comment]
Shifter Ward => Down Ward

**Comment by Tempus** [comment]
Cow Ward
In Ward
On Ward
Up Ward
Re Ward
Toe Ward
Tow Ward
Pow Ward
Sky Ward
For Ward
Awk Ward
Stew Ward
Out Ward
Back Ward
Ward Robe
Wind Ward
Sun Ward
After Ward
North/South/East/West ward
Home Ward
Way Ward
Heaven Ward
Wards with Friends
Re Warding
Swardsmanship
Wardmonger
Wardsmith
Cross Ward (puzzle)
After Wards
Buzz Ward
Pass Ward
Ward Play (hehe)
Key Ward
Wardthy
Otherwardly
Stalward

**Comment by Tempus** [comment]
Fixed
