### ISSUE TITLE
I appreciate this isn't the right place to ask, but... [Read]

### ISSUE THREAD

**Issue by Alexowo** [Tempus/Disciple-Monster-Train#85]
I appreciate this isn't the right place to ask, but I figured I would tell you here since this is your most recently updated repository. In the contact page of your site the Discord username doesn't show the # number meaning I can't add you if I want to speak to you. Could you please give me your Discord username if that's alright? I'm wondering if I can speak to you about Newer Super Mario Bros. Wii if you were involved in that. (I hope I'm not getting any names wrong, but on the Soundtrack you were credited)

**Comment by Tempus** [comment]
Sure, Chronometrics#5226, my server link is https://discord.gg/Cs4kY4E

**Comment by RisingDusk** [comment]
Closing issue that isn't actually an issue.
